LMS/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from .import views, user_login
from django.conf import settings
from django.conf.urls.static import static
from .views import success_page, error_page

urlpatterns = [
    path('admin', admin.site.urls),

    path('base', views.BASE, name='base'),
    path('404', views.PAGE_NOT_FOUND, name='404'),
    path('', views.HOME, name='home'),
    path('courses', views.SINGLE_COURSE, name='single_course'),
    path('courses/filter-data', views.filter_data, name="filter-data"),
    path('search', views.SEARCH_COURSE, name="search_course"),
    path('course/<slug:slug>', views.COURSE_DETAILS, name='course_details'),
    path('contact', views.CONTACT_US, name='contact_us'),
    path('about', views.ABOUT_US, name='about_us'),
    path('accounts/register', user_login.REGISTER, name='register'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('doLogin', user_login.DO_LOGIN, name='doLogin'),
    path('accounts/profile', user_login.PROFILE, name='profile'),
    path('accounts/profile/update', user_login.PROFILE_UPDATE, name='profile_update'),

    path('checkout/<slug:slug>',views.CHECKOUT, name='checkout'),
    path('my-course',views.MY_COURSE, name='my_course'),

    path('payment/', include('payment_module.urls')),
    path('success_page/',views.success_page, name="success_page"),
    path('error_page/', error_page, name="error_page"),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save

# Create your models here.

class Categories(models.Model):
    icon = models.CharField(max_length=200,null=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def get_all_category(self):
        return Categories.objects.all().order_by('id')

    class Meta:
        verbose_name_plural = "Categories"


class Author(models.Model):
    author_profile = models.ImageField(upload_to="Media/author")
    name = models.CharField(max_length=100, null=True)
    about_author = models.TextField()

    def __str__(self):
        return self.name
        
class Level(models.Model):
    name = models.CharField(max_length = 100)

    def __str__(self):
        return self.name

class Language(models.Model):
    language = models.CharField(max_length=100)

    def __str__(self):
        return self.language

class Course(models.Model):
    STATUS = (
        ('PUBLISH','PUBLISH'),
        ('DRAFT', 'DRAFT'),
    )

    featured_image = models.ImageField(upload_to="Media/featured_img",null=True)
    featured_video = models.CharField(max_length=300,null=True)
    title = models.CharField(max_length=500)
    created_at = models.DateField(auto_now_add=True)
    author = models.ForeignKey(Author,on_delete=models.CASCADE,null=True)
    category = models.ForeignKey(Categories,on_delete=models.CASCADE)
    level = models.ForeignKey(Level,on_delete=models.CASCADE, null=True)
    description = models.TextField()
    price = models.IntegerField(null=True,default=0)
    discount = models.IntegerField(null=True)
    language = models.ForeignKey(Language,on_delete=models.CASCADE, null=True)
    Deadline = models.CharField(max_length=100,null=True)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    status = models.CharField(choices=STATUS,max_length=100,null=True)
    Certificate = models.CharField(null=True, max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("course_details", kwargs={'slug': self.slug})

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Course.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, Course)

class What_you_learn(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    points = models.CharField(max_length=500)

    def __str__(self):
        return self.points

    class Meta:
        verbose_name_plural = "What_you_learn"


class Requirements(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    points = models.CharField(max_length=500)

    def __str__(self):
        return self.points

    class Meta:
        verbose_name_plural = "Requirements"

class Lesson(models.Model):
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name + " - " + self.course.title

class Video(models.Model):
    serial_number = models.IntegerField(null=True)
    thumbnail = models.ImageField(upload_to="Media/Yt_Thumbnail",null=True)
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson,on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    youtube_id = models.CharField(max_length=200)
    time_duration = models.IntegerField(null = True)
    preview = models.BooleanField(default=False)

    def __str__(self):
        return self.title

class UserCourse(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    paid = models.BooleanField(default=0)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.first_name + " - " + self.course.title

templates/Main/single_course.html
{% extends 'base.html' %}
{% block title %}Course{% endblock %}
{% load static %}
{% block content %}
{% load course_tags %}

<script>
    $(document).ready(function () {

        $(".filter-checkbox").on('click', function () {
            var filter_object = {};
            $(".filter-checkbox").each(function (index, ele) {
                var filter_value = $(this).val();
                var filter_key = $(this).data('filter');
                console.log(filter_key, filter_value);
                filter_object[filter_key] = Array.from(document.querySelectorAll('input[data-filter=' + filter_key + ']:checked')).map(function (el) {
                    return el.value;
                });
            });

            $.ajax({
                url:'{% url 'filter-data' %}',
                data: filter_object,
                dataType: 'json',
                success: function(res) {
                    console.log(res)
                    $("#filteredCourses").html(res.data);
                    var filter_value = $(this).val();
                    var filter_key = $(this).data('filter');
                }
            });
        });
    });
</script>


<!-- PAGE TITLE
    ================================================== -->
<header class="py-8 py-md-8 mb-5" style="background-image: none;">
    <div class="container text-center py-xl-2">
        <h1 class="display-4 fw-semi-bold mb-0">Courses</h1>
    </div>
    <!-- Img -->
    <img class="d-none img-fluid" src="...html" alt="...">
</header>

<!-- COURSE LIST V2
    ================================================== -->
<div class="container">
    <div class="row">
        <div class="col-xl-4 mb-5 mb-xl-0">
            <!-- SIDEBAR FILTER
                ================================================== -->
            <div class=" vertical-scroll" id="courseSidebar">
                <div class="border rounded mb-6 @@widgetBG">
                    <!-- Heading -->
                    <div id="coursefilter1">
                        <h4 class="mb-0">
                            <button
                                class="p-6 text-dark fw-medium d-flex align-items-center collapse-accordion-toggle line-height-one"
                                type="button" data-bs-toggle="collapse" data-bs-target="#coursefiltercollapse1"
                                aria-expanded="true" aria-controls="coursefiltercollapse1">
                                Category
                                <span class="ms-auto text-dark d-flex">
                                    <!-- Icon -->
                                    <svg width="15" height="2" viewBox="0 0 15 2" fill="none"
                                        xmlns="http://www.w3.org/2000/svg">
                                        <rect width="15" height="2" fill="currentColor" />
                                    </svg>

                                    <svg width="15" height="16" viewBox="0 0 15 16" fill="none"
                                        xmlns="http://www.w3.org/2000/svg">
                                        <path d="M0 7H15V9H0V7Z" fill="currentColor" />
                                        <path d="M6 16L6 8.74228e-08L8 0L8 16H6Z" fill="currentColor" />
                                    </svg>

                                </span>
                            </button>
                        </h4>
                    </div>

                    <div id="coursefiltercollapse1" class="collapse show mt-n2 px-6 pb-6"
                        aria-labelledby="coursefilter1" data-parent="#courseSidebar">
                        <ul class="list-unstyled list-group list-checkbox">
                            {% for i in category %}
                            <li class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input filter-checkbox"
                                    id="category-{{i.id}}" data-filter="category" value="{{i.id}}">
                                <label class="custom-control-label font-size-base" for="category-{{i.id}}">{{i.name}}
                                    ({{i.course_set.all.count}})</label>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

                <div class="border rounded mb-6 @@widgetBG">
                    <!-- Heading -->
                    <div id="coursefilter3">
                        <h4 class="mb-0">
                            <button
                                class="p-6 text-dark fw-medium d-flex align-items-center collapse-accordion-toggle line-height-one"
                                type="button" data-bs-toggle="collapse" data-bs-target="#coursefiltercollapse3"
                                aria-expanded="true" aria-controls="coursefiltercollapse3">
                                Price
                                <span class="ms-auto text-dark d-flex">
                                    <!-- Icon -->
                                    <svg width="15" height="2" viewBox="0 0 15 2" fill="none"
                                        xmlns="http://www.w3.org/2000/svg">
                                        <rect width="15" height="2" fill="currentColor" />
                                    </svg>

                                    <svg width="15" height="16" viewBox="0 0 15 16" fill="none"
                                        xmlns="http://www.w3.org/2000/svg">
                                        <path d="M0 7H15V9H0V7Z" fill="currentColor" />
                                        <path d="M6 16L6 8.74228e-08L8 0L8 16H6Z" fill="currentColor" />
                                    </svg>

                                </span>
                            </button>
                        </h4>
                    </div>

                    <div id="coursefiltercollapse3" class="collapse show mt-n2 px-6 pb-6"
                        aria-labelledby="coursefilter3" data-parent="#courseSidebar">
                        <ul class="list-unstyled list-group list-checkbox">
                            <li class="custom-control custom-radio">
                                <input type="radio" id="price-1" name="customRadio"
                                    class="custom-control-input filter-checkbox" value="PriceAll" data-filter="price">
                                <label class="custom-control-label font-size-base" for="price-1">All ({{course.all.count}})</label>
                            </li>
                            <li class="custom-control custom-radio">
                                <input type="radio" id="price-2" name="customRadio"
                                    class="custom-control-input filter-checkbox" value="PriceFree" data-filter="price">
                                <label class="custom-control-label font-size-base" for="price-2">Free ({{FreeCourse_count}})</label>
                            </li>
                            <li class="custom-control custom-radio">
                                <input type="radio" id="price-3" name="customRadio"
                                    class="custom-control-input filter-checkbox" value="PricePaid" data-filter="price">
                                <label class="custom-control-label font-size-base" for="price-3">Paid ({{PaidCourse_count}})</label>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="border rounded mb-6 @@widgetBG">
                    <!-- Heading -->
                    <div id="coursefilter4">
                        <h4 class="mb-0">
                            <button
                                class="p-6 text-dark fw-medium d-flex align-items-center collapse-accordion-toggle line-height-one"
                                type="button" data-bs-toggle="collapse" data-bs-target="#coursefiltercollapse4"
                                aria-expanded="true" aria-controls="coursefiltercollapse4">
                                Level
                                <span class="ms-auto text-dark d-flex">
                                    <!-- Icon -->
                                    <svg width="15" height="2" viewBox="0 0 15 2" fill="none"
                                        xmlns="http://www.w3.org/2000/svg">
                                        <rect width="15" height="2" fill="currentColor" />
                                    </svg>

                                    <svg width="15" height="16" viewBox="0 0 15 16" fill="none"
                                        xmlns="http://www.w3.org/2000/svg">
                                        <path d="M0 7H15V9H0V7Z" fill="currentColor" />
                                        <path d="M6 16L6 8.74228e-08L8 0L8 16H6Z" fill="currentColor" />
                                    </svg>

                                </span>
                            </button>
                        </h4>
                    </div>

                    <div id="coursefiltercollapse4" class="collapse show mt-n2 px-6 pb-6"
                        aria-labelledby="coursefilter4" data-parent="#courseSidebar">
                        <ul class="list-unstyled list-group list-checkbox">
                            {% for i in level %}
                                <li class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input filter-checkbox" id="level-{{i.id}}" value="{{i.id}}" data-filter="level">
                                    <label class="custom-control-label font-size-base" for="level-{{i.id}}">{{i.name}} ({{i.course_set.all.count}})</label>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

            </div>

        </div>

        <div class="col-xl-8">
            <div class="row row-cols-md-2 mb-3 " id="filteredCourses">
                {% for i in course%}
                <div class="col-md pb-4 pb-md-7">
                    <!-- Card -->
                    <div class="card border shadow p-2 lift sk-fade"  style="height:400px;">
                        <!-- Image -->
                        <div class="card-zoom position-relative">

                            <a href="{{i.get_absolute_url}}" class="card-img sk-thumbnail d-block">
                                <img class="rounded shadow-light-lg" src="{{i.featured_image}}" alt="...">
                            </a>

                            <span
                                class="badge sk-fade-bottom badge-lg badge-primary badge-pill badge-float bottom-0 left-0 mb-4 ms-4">
                                <span class="text-white text-uppercase fw-bold font-size-xs">Discount {{i.discount}} %</span>
                            </span>
                        </div>

                        <!-- Footer -->
                        <div class="card-footer px-2 pb-2 mb-1 pt-4 position-relative">
                            <a href="instructors-single.html" class="d-block">
                                <div
                                    class="avatar sk-fade-right avatar-xl badge-float position-absolute top-0 right-0 mt-n6 me-5 rounded-circle shadow border border-white border-w-lg">
                                    <img src="{{i.author.author_profile}}" alt="..." class="avatar-img rounded-circle">
                                </div>
                            </a>

                            <!-- Preheading -->
                            <a href="{{i.get_absolute_url}}"><span
                                    class="mb-1 d-inline-block text-gray-800">{{i.category}}</span></a>

                            <!-- Heading -->
                            <div class="position-relative">
                                <a href="{{i.get_absolute_url}}" class="d-block stretched-link">
                                    <h4 class="line-clamp-2 h-md-48 h-lg-58 me-md-6 me-lg-10 me-xl-4 mb-2">{{i.title}}
                                    </h4>
                                </a>

                                <div class="row mx-n2 align-items-end">
                                    <div class="col px-2">
                                    </div>

                                    {% if i.price == 0 %}
                                        <div class="col-auto px-2 text-right">
                                            <ins class="h4 mb-0 d-block mb-lg-n1"><a href="#" class="badge badge-primary">Free</a></ins>
                                        </div>
                                    {% else %}
                                        <div class="col-auto px-2 text-right">
                                            <del class="font-size-sm">Rs. {{i.price}}</del>
                                            <ins class="h4 mb-0 d-block mb-lg-n1">Rs. {% discount_calculation i.price i.discount %}</ins>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor%}
            </div>

        </div>
    </div>
</div>

{% endblock %}